spring.datasource.url=jdbc:mysql://hari-mysql21-hariharan-4b4e.c.aivencloud.com:18669/defaultdb?ssl-mode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_P47h8fTsbBuY3pRxExk

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
